name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:  # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Sync upstream
        run: |
          git remote add upstream https://github.com/stuinfla/chrisdavidsalon.git
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit
          git push origin main